<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>17_chkPrimaryEmailUAT</name>
   <tag></tag>
   <elementGuidId>f3d9cd3f-6588-495f-a813-57c64142ddd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@VALUE='EMAIL']/parent::span/parent::div/parent::td/parent::tr/td[5]/div/span/input)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
