<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>22_btnDeleteContact</name>
   <tag></tag>
   <elementGuidId>98f5cad5-c802-4c75-b06e-6d062c163e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr/td/table/tbody/tr/td[5]/table/tbody/tr/td/table/tbody/tr/td/div/div/div[2]/div[2]/div[2]/button[contains(text(),'Delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
