<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>32_chkPrimaryFAX</name>
   <tag></tag>
   <elementGuidId>414f6c9c-d0ae-4159-b313-66ca48917429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@VALUE='FAX']/parent::span/parent::div/parent::td/parent::tr/td[5]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
