<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>33_fldSearchMS_1</name>
   <tag></tag>
   <elementGuidId>1f159866-9833-4ce5-a08e-5beca054a312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div[3]/div[2]/div[1]/div[2]/table/tbody/tr/td/table/tbody/tr/td[1]/table/tbody/tr/td/table/tbody/tr/td/div/div[2]/div[2]/div[4]/table/tbody[1]/tr[1]/td[2]/div/span/a/i
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
