<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>32_fldBASTDate</name>
   <tag></tag>
   <elementGuidId>619316c5-dcbc-444a-b5f9-a646bc6611b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div[1]/div[2]/div[1]/div/div/div/div[1]/div[3]/table/tbody[1]/tr[3]/td[4]/div/table/tbody/tr/td/table/tbody/tr/td[1]/span/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
