<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01_cbFrequencyMonthly</name>
   <tag></tag>
   <elementGuidId>e2a9689c-7119-481c-bad8-f1184f8bd77a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'z-combobox-open')]/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mNUF380</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f57de839-f49d-40df-8063-459f92dbfcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mNUF380</value>
      <webElementGuid>e64846c5-b57b-4c1e-acee-b3f116545802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>65130118-56ee-4b61-b8c7-387200723c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AL BAI WA AL ISTIJAR</value>
      <webElementGuid>2809df7a-89a5-4aa1-9365-9b4c4c3f9a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mNUF380&quot;)</value>
      <webElementGuid>a6c1330e-7c4b-44f6-99ac-668b8b2b8e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mNUF380']</value>
      <webElementGuid>5c35edd2-ba5b-4ef1-8c5d-039dfd89f060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mNUFki-cave']/li</value>
      <webElementGuid>32d4e0ad-3516-4101-89c8-e7fa46ce1242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>5dbc0245-c985-4289-8421-03b8b5b51c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::li[1]</value>
      <webElementGuid>6c6c4301-0932-400a-a6bd-acbee38dcba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUSYARAKAH MUTANAQISHAH'])[1]/preceding::li[1]</value>
      <webElementGuid>949286a3-9fdc-4f7f-b96b-0185aa5f90a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li</value>
      <webElementGuid>4e27ec6e-18ab-48cc-94fe-bd5bd6429337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mNUF380' and (text() = 'AL BAI WA AL ISTIJAR' or . = 'AL BAI WA AL ISTIJAR')]</value>
      <webElementGuid>1b946e67-81d9-4ae0-bfa6-35be3f5afa56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
