<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02_cbFrequencyNumberRow2</name>
   <tag></tag>
   <elementGuidId>40b9c67e-0a9c-4ada-8df6-cfdcc68b0485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'z-combobox-open')]/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mNUF380</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5de8527f-f43e-4309-9b2d-236bce3d51e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mNUF380</value>
      <webElementGuid>25aaf1e1-a43d-462a-9e96-2bf9bdbbae68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>c700f6c8-cc66-4bd7-8485-35c316ef653c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AL BAI WA AL ISTIJAR</value>
      <webElementGuid>583e20d7-3f18-47b0-8477-6a312e194bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mNUF380&quot;)</value>
      <webElementGuid>a02db20d-2e56-4075-8750-b5fb06594b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mNUF380']</value>
      <webElementGuid>2bf471f5-ec7e-4e70-824b-fd8d09520416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mNUFki-cave']/li</value>
      <webElementGuid>d7443f04-78cc-462b-adce-b1225ee3fef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>0a2f5172-4d44-41e1-ae20-3a310b4b9b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::li[1]</value>
      <webElementGuid>ba6d7906-a92c-49d1-8870-faa580304b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUSYARAKAH MUTANAQISHAH'])[1]/preceding::li[1]</value>
      <webElementGuid>7dfe6d7d-e612-46a0-9ab0-386e07932982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li</value>
      <webElementGuid>ce77b657-4e9e-4199-9d3c-00cd92d1f758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mNUF380' and (text() = 'AL BAI WA AL ISTIJAR' or . = 'AL BAI WA AL ISTIJAR')]</value>
      <webElementGuid>bab8d6ac-b1b0-4fe6-aa5b-e114684a27de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
