<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>26_cbNationality</name>
   <tag></tag>
   <elementGuidId>c18bebbe-cb77-43ba-91a3-30265df73154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='z-page']//div[1]/div/div[3]/div[3]/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[8]/div[2]/div[1]/div/div[1]/div[3]/table/tbody[1]/tr/td/div/table/tbody/tr/td/table/tbody/tr/td[1]/table/tbody/tr/td/table/tbody/tr[1]/td/div/div[2]/div/div[3]/table/tbody[1]/tr[22]/td[2]/div/span/input
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
