<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>ORDER SUBMIT</name>
   <tag></tag>
   <elementGuidId>c068983b-5053-4a22-9d64-91a44d6df7e0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;coyId\&quot;: \&quot;01\&quot;,\n    \&quot;orderNo\&quot;: \&quot;${orderNo}\&quot;,\n    \&quot;sourceInput\&quot;: \&quot;F\&quot;,\n    \&quot;orderDate\&quot;: \&quot;2025-12-08 04:26:39\&quot;,\n    \&quot;businessCategory\&quot;: \&quot;RETAIL\&quot;,\n    \&quot;customerCategory\&quot;: \&quot;003\&quot;,\n    \&quot;progCode\&quot;: \&quot;MP02\&quot;,\n    \&quot;businessUnit\&quot;: \&quot;${bussUnit}\&quot;,\n    \&quot;preOrderNo\&quot;: \&quot;${orderNo}\&quot;,\n    \&quot;subBusinessUnit\&quot;: null,\n    \&quot;platform\&quot;: \&quot;${platform}\&quot;,\n    \&quot;creditObjective\&quot;: \&quot;PP004\&quot;,\n    \&quot;subPlatform\&quot;: null,\n    \&quot;officeCode\&quot;: \&quot;${officeCode}\&quot;,\n    \&quot;sectorIndustry\&quot;: null,\n    \&quot;serviceOfficeCode\&quot;: \&quot;${serviceOfficeCode}\&quot;,\n    \&quot;salesOffice\&quot;: null,\n    \&quot;scoredBy\&quot;: null,\n    \&quot;caCoordinator\&quot;: \&quot;K1050109\&quot;,\n    \&quot;caCoordinatorNik\&quot;: \&quot;17481\&quot;,\n    \&quot;csId\&quot;: \&quot;1095\&quot;,\n    \&quot;salesId\&quot;: null,\n    \&quot;pgcId\&quot;: null,\n    \&quot;mceId\&quot;: null,\n    \&quot;agentFifadaId\&quot;: null,\n    \&quot;agentFifadaName\&quot;: null,\n    \&quot;ocptType\&quot;: \&quot;1\&quot;,\n    \&quot;createdBy\&quot;: \&quot;${createdBy}\&quot;,\n    \&quot;createdDate\&quot;: \&quot;2025-09-03 17:00:00\&quot;,\n    \&quot;custNo\&quot;: \&quot;DAF\&quot;,\n    \&quot;custId\&quot;: \&quot;${custId}\&quot;,\n    \&quot;custTitle\&quot;: null,\n    \&quot;custName\&quot;: \&quot;${custName}\&quot;,\n    \&quot;custNikName\&quot;: \&quot;${custNikName}\&quot;,\n    \&quot;birthDate\&quot;: \&quot;${birthDate}\&quot;,\n    \&quot;birthPlace\&quot;: \&quot;${birthPlace}\&quot;,\n    \&quot;sex\&quot;: \&quot;${sex}\&quot;,\n    \&quot;mothersName\&quot;: \&quot;${mothersName}\&quot;,\n    \&quot;education\&quot;: \&quot;S1\&quot;,\n    \&quot;maritalStatus\&quot;: \&quot;S\&quot;,\n    \&quot;houseStatus\&quot;: \&quot;H06\&quot;,\n    \&quot;occupationOnID\&quot;: \&quot;04\&quot;,\n    \&quot;occupation\&quot;: \&quot;04\&quot;,\n    \&quot;subOccupation\&quot;: null,\n    \&quot;custAddress\&quot;: \&quot;JAUH\&quot;,\n    \&quot;custRT\&quot;: \&quot;5\&quot;,\n    \&quot;custRW\&quot;: \&quot;5\&quot;,\n    \&quot;custProvCode\&quot;: \&quot;032\&quot;,\n    \&quot;custProv\&quot;: null,\n    \&quot;custCityCode\&quot;: \&quot;03276\&quot;,\n    \&quot;custCity\&quot;: null,\n    \&quot;custKecCode\&quot;: \&quot;0327605\&quot;,\n    \&quot;custKec\&quot;: \&quot;KEC SUKMAJAYA\&quot;,\n    \&quot;custKelCode\&quot;: \&quot;0327605006\&quot;,\n    \&quot;custKel\&quot;: \&quot;KEL BAKTIJAYA\&quot;,\n    \&quot;custSubZip\&quot;: \&quot;0001\&quot;,\n    \&quot;custZip\&quot;: \&quot;16418\&quot;,\n    \&quot;custMobilePhone1\&quot;: \&quot;085773216917\&quot;,\n    \&quot;custMobilePhone2\&quot;: null,\n    \&quot;custOfficePhoneArea\&quot;: null,\n    \&quot;custOfficePhone\&quot;: null,\n    \&quot;custOfficeExt\&quot;: null,\n    \&quot;custPhoneArea\&quot;: null,\n    \&quot;custPhone\&quot;: null,\n    \&quot;custEmail\&quot;: null,\n    \&quot;domAddress\&quot;: null,\n    \&quot;domRT\&quot;: null,\n    \&quot;domRW\&quot;: null,\n    \&quot;domProvCode\&quot;: null,\n    \&quot;domCityCode\&quot;: null,\n    \&quot;domKecCode\&quot;: null,\n    \&quot;domKelCode\&quot;: null,\n    \&quot;domSubZip\&quot;: null,\n    \&quot;domZip\&quot;: null,\n    \&quot;verfAddress\&quot;: \&quot;JAUH\&quot;,\n    \&quot;verfRT\&quot;: \&quot;5\&quot;,\n    \&quot;verfRW\&quot;: \&quot;5\&quot;,\n    \&quot;verfProvCode\&quot;: \&quot;032\&quot;,\n    \&quot;verfCityCode\&quot;: \&quot;03276\&quot;,\n    \&quot;verfKecCode\&quot;: \&quot;0327605\&quot;,\n    \&quot;verfKelCode\&quot;: \&quot;0327605006\&quot;,\n    \&quot;verfSubZip\&quot;: \&quot;0001\&quot;,\n    \&quot;verfZip\&quot;: \&quot;16418\&quot;,\n    \&quot;poolingFlag\&quot;: null,\n    \&quot;currency\&quot;: \&quot;IDR\&quot;,\n    \&quot;promoID\&quot;: null,\n    \&quot;objectFinanced\&quot;: [\n        {\n            \&quot;supplierCode\&quot;: null,\n            \&quot;objectCode\&quot;: \&quot;${objectCode}\&quot;,\n            \&quot;objectGroup\&quot;: \&quot;${objectGroup}\&quot;,\n            \&quot;objectColour\&quot;: null,\n            \&quot;newUsed\&quot;: \&quot;N\&quot;,\n            \&quot;objectYear\&quot;: \&quot;2023\&quot;,\n            \&quot;purposeType\&quot;: null,\n            \&quot;usageType\&quot;: null,\n            \&quot;currency\&quot;: \&quot;IDR\&quot;,\n            \&quot;objectQty\&quot;: 1,\n            \&quot;objectPrice\&quot;: \&quot;${objectPrice}\&quot;,\n            \&quot;grossDpDealer\&quot;: null,\n            \&quot;grossDpFIF\&quot;: null,\n            \&quot;installmentAmount\&quot;: 0,\n            \&quot;insuranceCompany\&quot;: null,\n            \&quot;insuranceProduct\&quot;: null,\n            \&quot;insuranceRateNo\&quot;: null,\n            \&quot;schemeObject\&quot;: null,\n            \&quot;bpkbName\&quot;: \&quot;RAENOVALDY\&quot;,\n            \&quot;sendVia\&quot;: null,\n            \&quot;noRangka\&quot;: \&quot;${noRangka}\&quot;,\n            \&quot;noMesin\&quot;: \&quot;${noMesin}\&quot;,\n            \&quot;noPolisi\&quot;: \&quot;B6789JKL\&quot;,\n            \&quot;noBPKB\&quot;: \&quot;BPKB77TTT NO\&quot;,\n            \&quot;noKwitansi\&quot;: null,\n            \&quot;balikNama\&quot;: null,\n            \&quot;seqNo\&quot;: \&quot;1\&quot;,\n            \&quot;isSign\&quot;: null,\n            \&quot;akadSyariaCode\&quot;: null,\n            \&quot;needPromo\&quot;: null,\n            \&quot;refiValueCust\&quot;: null,\n            \&quot;bpkbOccu\&quot;: \&quot;PEGAWAI SWASTA\&quot;,\n            \&quot;bpkbSameName\&quot;: \&quot;${bpkbSameName}\&quot;,\n            \&quot;bpkbAddress\&quot;: \&quot;JAUH\&quot;,\n            \&quot;bpkbRt\&quot;: \&quot;5\&quot;,\n            \&quot;bpkbRw\&quot;: \&quot;5\&quot;,\n            \&quot;bpkbZip\&quot;: \&quot;16418\&quot;,\n            \&quot;bpkbSubZip\&quot;: \&quot;0001\&quot;,\n            \&quot;bpkbCityCode\&quot;: \&quot;03276\&quot;,\n            \&quot;bpkbCity\&quot;: \&quot;KOTA DEPOK\&quot;,\n            \&quot;bpkbKecCode\&quot;: \&quot;0327605\&quot;,\n            \&quot;bpkbKec\&quot;: \&quot;KEC SUKMAJAYA\&quot;,\n            \&quot;bpkbKelCode\&quot;: \&quot;0327605006\&quot;,\n            \&quot;bpkbKel\&quot;: \&quot;KEL BAKTIJAYA\&quot;,\n            \&quot;bpkbProvCode\&quot;: \&quot;032\&quot;,\n            \&quot;bpkbProv\&quot;: \&quot;PROV JAWA BARAT\&quot;,\n            \&quot;bpkbIdType\&quot;: null,\n            \&quot;bpkbIdNo\&quot;: null,\n            \&quot;collType\&quot;: \&quot;1\&quot;,\n            \&quot;collKind\&quot;: \&quot;1\&quot;,\n            \&quot;insInclCrdt\&quot;: \&quot;N\&quot;,\n            \&quot;invFlag\&quot;: \&quot;N\&quot;,\n            \&quot;amountToBeTransfer\&quot;: \&quot;${amountToBeTransfer}\&quot;,\n            \&quot;kilometer\&quot;: 10003,\n            \&quot;objModel\&quot;: \&quot;A1F02N37M1 AT\&quot;,\n            \&quot;objType\&quot;: \&quot;A1F02N37M1 AT\&quot;,\n            \&quot;objBrand\&quot;: \&quot;HONDA\&quot;,\n            \&quot;objDesc\&quot;: \&quot;VARIO 125 CBS ISS\&quot;,\n            \&quot;aabObjectCode\&quot;: null,\n            \&quot;amountCreditObjective\&quot;: \&quot;${amountCreditObjective}\&quot;,\n            \&quot;supplierAgentCode\&quot;: null,\n            \&quot;stnkNo\&quot;: null,\n            \&quot;stnkValidUntil\&quot;: \&quot;2024-12-02\&quot;\n        }\n    ],\n    \&quot;documents\&quot;: null,\n    \&quot;marketingSchemeContract\&quot;: null,\n    \&quot;structureCredit\&quot;: {\n        \&quot;tenor\&quot;: \&quot;${tenor}\&quot;,\n        \&quot;top\&quot;: \&quot;${top}\&quot;,\n        \&quot;periode\&quot;: \&quot;${periode}\&quot;,\n        \&quot;periodeType\&quot;: \&quot;M\&quot;,\n        \&quot;advArrear\&quot;: \&quot;AR\&quot;,\n        \&quot;calculationMethod\&quot;: null,\n        \&quot;calculationBy\&quot;: null,\n        \&quot;interestRate\&quot;: null,\n        \&quot;interestType\&quot;: \&quot;${interestType}\&quot;,\n        \&quot;adminFee\&quot;: 0,\n        \&quot;monthInst\&quot;: \&quot;${monthInst}\&quot;,\n        \&quot;topDaf\&quot;: null,\n        \&quot;intrRlMeth\&quot;: \&quot;02\&quot;,\n        \&quot;insInclCrdt\&quot;: \&quot;N\&quot;,\n        \&quot;price\&quot;: 23000000,\n        \&quot;choiceInstRate\&quot;: \&quot;1\&quot;\n    },\n    \&quot;soCode\&quot;: \&quot;S04\&quot;,\n    \&quot;surveyStat\&quot;: null,\n    \&quot;isHoliday\&quot;: \&quot;N\&quot;,\n    \&quot;isCreditLife\&quot;: null,\n    \&quot;aoId\&quot;: null,\n    \&quot;npwpNo\&quot;: null,\n    \&quot;ppdcfPaid\&quot;: null,\n    \&quot;isSign\&quot;: \&quot;Y\&quot;,\n    \&quot;purpose\&quot;: \&quot;PP004\&quot;,\n    \&quot;needPromo\&quot;: \&quot;N\&quot;,\n    \&quot;surveyComm\&quot;: null,\n    \&quot;noOfDepends\&quot;: 0,\n    \&quot;serviceYear\&quot;: null,\n    \&quot;serviceMonth\&quot;: 0,\n    \&quot;monthlyIncome\&quot;: 9000000,\n    \&quot;monthlyExpense\&quot;: 2000000,\n    \&quot;spouseIncome\&quot;: 0,\n    \&quot;otherIncome\&quot;: 0,\n    \&quot;officeName\&quot;: null,\n    \&quot;orderAddr\&quot;: {\n        \&quot;idCustAddr\&quot;: \&quot;JAUH\&quot;,\n        \&quot;idCustCityCode\&quot;: \&quot;03276\&quot;,\n        \&quot;idCustCity\&quot;: \&quot;KOTA DEPOK\&quot;,\n        \&quot;idCustRt\&quot;: \&quot;5\&quot;,\n        \&quot;idCustRw\&quot;: \&quot;5\&quot;,\n        \&quot;idCustZip\&quot;: \&quot;16418\&quot;,\n        \&quot;idCustSubZip\&quot;: \&quot;0001\&quot;,\n        \&quot;idCustKelCode\&quot;: \&quot;0327605006\&quot;,\n        \&quot;idCustKel\&quot;: \&quot;KEL BAKTIJAYA\&quot;,\n        \&quot;idCustKecCode\&quot;: \&quot;0327605\&quot;,\n        \&quot;idCustKec\&quot;: \&quot;KEC SUKMAJAYA\&quot;,\n        \&quot;idCustProvCode\&quot;: \&quot;032\&quot;,\n        \&quot;idCustProv\&quot;: \&quot;PROV JAWA BARAT\&quot;,\n        \&quot;collecAddr\&quot;: null,\n        \&quot;collecCityCode\&quot;: null,\n        \&quot;collecCity\&quot;: null,\n        \&quot;collecRt\&quot;: null,\n        \&quot;collecRw\&quot;: null,\n        \&quot;collecZip\&quot;: null,\n        \&quot;collecSubZip\&quot;: null,\n        \&quot;collecKelCode\&quot;: null,\n        \&quot;collecKel\&quot;: null,\n        \&quot;collecKecCode\&quot;: null,\n        \&quot;collecKec\&quot;: null,\n        \&quot;collecProvCode\&quot;: null,\n        \&quot;collecProv\&quot;: null,\n        \&quot;officeName\&quot;: null,\n        \&quot;offAddr\&quot;: null,\n        \&quot;offCityCode\&quot;: null,\n        \&quot;offCity\&quot;: null,\n        \&quot;offRt\&quot;: null,\n        \&quot;offRw\&quot;: null,\n        \&quot;offZip\&quot;: null,\n        \&quot;offSubZip\&quot;: null,\n        \&quot;offProvCode\&quot;: null,\n        \&quot;offProv\&quot;: null,\n        \&quot;offKelCode\&quot;: null,\n        \&quot;offKel\&quot;: null,\n        \&quot;offKecCode\&quot;: null,\n        \&quot;offKec\&quot;: null,\n        \&quot;offFixphArea\&quot;: null,\n        \&quot;offFixphone\&quot;: null,\n        \&quot;emerName\&quot;: \&quot;BOGI\&quot;,\n        \&quot;emerHub\&quot;: null,\n        \&quot;emerAddr\&quot;: \&quot;JAUH\&quot;,\n        \&quot;emerCityCode\&quot;: \&quot;01707\&quot;,\n        \&quot;emerCity\&quot;: \&quot;KABUPATEN LEBONG\&quot;,\n        \&quot;emerRt\&quot;: \&quot;5\&quot;,\n        \&quot;emerRw\&quot;: \&quot;6\&quot;,\n        \&quot;emerKelCode\&quot;: \&quot;0170708008\&quot;,\n        \&quot;emerKel\&quot;: \&quot;KEL UJUNG TANJUNG DUA\&quot;,\n        \&quot;emerKecCode\&quot;: \&quot;0170708\&quot;,\n        \&quot;emerKec\&quot;: \&quot;KEC LEBONG SAKTI\&quot;,\n        \&quot;emerProvCode\&quot;: \&quot;017\&quot;,\n        \&quot;emerProv\&quot;: \&quot;PROV BENGKULU\&quot;,\n        \&quot;emerFixphArea\&quot;: null,\n        \&quot;emerFixphone\&quot;: null,\n        \&quot;emerMobphone\&quot;: \&quot;08577392256\&quot;,\n        \&quot;emerMobphone2\&quot;: null,\n        \&quot;emerZip\&quot;: \&quot;39267\&quot;,\n        \&quot;emerSubZip\&quot;: null,\n        \&quot;identType\&quot;: \&quot;01\&quot;,\n        \&quot;identityNo\&quot;: \&quot;3114050501850036\&quot;,\n        \&quot;mailRt\&quot;: \&quot;5\&quot;,\n        \&quot;mailRw\&quot;: \&quot;5\&quot;,\n        \&quot;mailSubZip\&quot;: null,\n        \&quot;mailZip\&quot;: \&quot;16418\&quot;,\n        \&quot;mailCityCode\&quot;: \&quot;3276\&quot;,\n        \&quot;mailCity\&quot;: \&quot;Kota Depok\&quot;,\n        \&quot;mailKecCode\&quot;: \&quot;3276030\&quot;,\n        \&quot;mailKec\&quot;: \&quot;Kec Sukma Jaya\&quot;,\n        \&quot;mailKelCode\&quot;: \&quot;3276030010\&quot;,\n        \&quot;mailKel\&quot;: \&quot;Kel Baktijaya\&quot;,\n        \&quot;mailProvCode\&quot;: \&quot;32\&quot;,\n        \&quot;mailProv\&quot;: \&quot;Prop Jawa Barat\&quot;,\n        \&quot;mailAddr\&quot;: \&quot;JAUH\&quot;\n    },\n    \&quot;orderSpouse\&quot;: {\n        \&quot;spouseName\&quot;: null,\n        \&quot;identityType\&quot;: null,\n        \&quot;identityNo\&quot;: null,\n        \&quot;birthPlace\&quot;: null,\n        \&quot;birthDate\&quot;: null,\n        \&quot;spouseOccupation\&quot;: null,\n        \&quot;spouseSubOccupation\&quot;: null,\n        \&quot;serviceYear\&quot;: null,\n        \&quot;serviceMonth\&quot;: null,\n        \&quot;noOfDepends\&quot;: null,\n        \&quot;officeName\&quot;: null,\n        \&quot;relationship\&quot;: null,\n        \&quot;hubungan1\&quot;: null,\n        \&quot;hubungan2\&quot;: null,\n        \&quot;hubungan3\&quot;: null,\n        \&quot;cekLingkungan1\&quot;: null,\n        \&quot;cekLingkungan2\&quot;: null,\n        \&quot;cekLingkungan3\&quot;: null,\n        \&quot;commentVerifikasi\&quot;: null\n    },\n    \&quot;orderDoc\&quot;: [],\n    \&quot;orderSign\&quot;: {\n        \&quot;sign01\&quot;: \&quot;Y\&quot;,\n        \&quot;sign02\&quot;: \&quot;N\&quot;,\n        \&quot;sign03\&quot;: \&quot;N\&quot;,\n        \&quot;fingerprint\&quot;: \&quot;N\&quot;\n    },\n    \&quot;unitAvailability\&quot;: null,\n    \&quot;surveyId\&quot;: \&quot;10500160\&quot;,\n    \&quot;surveyNik\&quot;: \&quot;17481\&quot;,\n    \&quot;totalDp\&quot;: 0,\n    \&quot;isAutoAppraisal\&quot;: 0,\n    \&quot;coriGrade\&quot;: null,\n    \&quot;pefindoGrade\&quot;: \&quot;D3\&quot;,\n    \&quot;reqId\&quot;: \&quot;0607FDAA-78F7-49D7-9A9B-F883622026A0\&quot;,\n    \&quot;pefindoScore\&quot;: 571,\n    \&quot;flagPefindo\&quot;: \&quot;1\&quot;,\n    \&quot;flagBlacklist\&quot;: null,\n    \&quot;categoryAppraisal\&quot;: \&quot;HIGH\&quot;,\n    \&quot;customerFullname\&quot;: \&quot;ANDY FIRMANSYAH\&quot;,\n    \&quot;flagCovadex\&quot;: \&quot;2\&quot;,\n    \&quot;custMainNo\&quot;: null,\n    \&quot;flagMatching\&quot;: \&quot;Y\&quot;,\n    \&quot;flagDukcapil\&quot;: \&quot;1\&quot;,\n    \&quot;flagRelaksasi\&quot;: null,\n    \&quot;branchOfficeID\&quot;: \&quot;${branchID}\&quot;,\n    \&quot;flagConfirmCust1\&quot;: \&quot;Y\&quot;,\n    \&quot;flagConfirmCust2\&quot;: \&quot;Y\&quot;,\n    \&quot;flagConfirmCust3\&quot;: \&quot;Y\&quot;,\n    \&quot;flagConfirmCust4\&quot;: \&quot;Y\&quot;,\n    \&quot;subPurpose\&quot;: \&quot;SP009\&quot;,\n    \&quot;statusKepemilikanRekening\&quot;: null,\n    \&quot;namaBank\&quot;: null,\n    \&quot;kodeBank\&quot;: null,\n    \&quot;noRekening\&quot;: null,\n    \&quot;namaRekening\&quot;: null,\n    \&quot;nikKeluarga\&quot;: null,\n    \&quot;namaKeluarga\&quot;: null,\n    \&quot;nomorKK\&quot;: null,\n    \&quot;flagValidasi\&quot;: null,\n    \&quot;flagTransfer\&quot;: \&quot;${flagTransfer}\&quot;,\n    \&quot;flagCloseOpen\&quot;: \&quot;${flagCloseOpen}\&quot;,\n    \&quot;seamlessId\&quot;: null,\n    \&quot;bankStatus\&quot;: null,\n    \&quot;purposeType\&quot;: null,\n    \&quot;gcid\&quot;: null,\n    \&quot;paymentType\&quot;: null,\n    \&quot;flagContract\&quot;: null,\n    \&quot;flagPopUp\&quot;: null,\n    \&quot;flagVoucher\&quot;: null,\n    \&quot;reffContractNo\&quot;: null,\n    \&quot;branchContractLama\&quot;: null,\n    \&quot;reffOrderNo\&quot;: \&quot;${reffOrderNo}\&quot;,\n    \&quot;voucher\&quot;: null,\n    \&quot;interestTypeLama\&quot;: null,\n    \&quot;tenorLama\&quot;: null,\n    \&quot;periodeLama\&quot;: null,\n    \&quot;angsuranKe\&quot;: \&quot;${angsuranKe}\&quot;,\n    \&quot;sisaTotalHutang\&quot;: null,\n    \&quot;totalHutangAwal\&quot;: null,\n    \&quot;kontrakAktif\&quot;: \&quot;${kontrakAktif}\&quot;,\n    \&quot;currentOverdue\&quot;: null,\n    \&quot;sisaBungaBerjalan\&quot;: null,\n    \&quot;plafondRekomendasi\&quot;: null,\n    \&quot;totalHutang\&quot;: \&quot;${totalHutang}\&quot;,\n    \&quot;sisaPokokHutang\&quot;: \&quot;${ssPokokHutang}\&quot;,\n    \&quot;sisaTenor\&quot;: \&quot;${sisaTenor}\&quot;,\n    \&quot;clopInsc\&quot;: null,\n    \&quot;flagCall12\&quot;: null,\n    \&quot;timeSpanDate\&quot;: \&quot;${timeSpanDate}\&quot;,\n    \&quot;contractActiveDate\&quot;: \&quot;${contractActDate}\&quot;,\n    \&quot;cycleAwal\&quot;: null,\n    \&quot;reffMaturityDate\&quot;: \&quot;2026-09-03 17:00:00\&quot;,\n    \&quot;reffPlatForm\&quot;: null,\n    \&quot;reffBusinessUnit\&quot;: null,\n    \&quot;reffObjectPrice\&quot;: null,\n    \&quot;reffGrossDp\&quot;: null,\n    \&quot;reffAdminPtContract\&quot;: null,\n    \&quot;reffAdminPaidContract\&quot;: null,\n    \&quot;collFee\&quot;: null,\n    \&quot;sisaSplittingRate\&quot;: null,\n    \&quot;angsuranBerjalan\&quot;: \&quot;${angBerjalan}\&quot;,\n    \&quot;denda\&quot;: null,\n    \&quot;flagNego\&quot;: null,\n    \&quot;amountNego\&quot;: null,\n    \&quot;statusNego\&quot;: null,\n    \&quot;terminationNo\&quot;: null,\n    \&quot;biroSource\&quot;: \&quot;PEFINDO\&quot;,\n    \&quot;scoreMessageCode\&quot;: null,\n    \&quot;scoreMessageDescription\&quot;: null,\n    \&quot;exclusionRuleCode\&quot;: null,\n    \&quot;exclusionRuleDescription\&quot;: null,\n    \&quot;flagBadFamily\&quot;: \&quot;4\&quot;,\n    \&quot;famContractActive\&quot;: null,\n    \&quot;famContractClose\&quot;: null,\n    \&quot;famWo\&quot;: null,\n    \&quot;famOverdue\&quot;: null,\n    \&quot;famPelsus\&quot;: null,\n    \&quot;famBa\&quot;: null,\n    \&quot;famRepo\&quot;: null,\n    \&quot;sourceInputOri\&quot;: \&quot;${sourceInputOri}\&quot;,\n    \&quot;flagClp\&quot;: \&quot;${flagClp}\&quot;,\n    \&quot;matchingFlagClp\&quot;: \&quot;${matchingFlagClp}\&quot;,\n    \&quot;autoSurvey\&quot;: false\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>b866e225-9dfe-4d9c-aae9-a53a9385868f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${token}</value>
      <webElementGuid>d60ba658-b24c-43ad-9352-ac070d096aea</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>http://10.17.25.108:8090/api/ordercmd/submit</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4023fe52-3e68-47b3-8c05-3cd9c865502c</id>
      <masked>false</masked>
      <name>orderNo</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>aaa2fa14-3c52-4e08-89b0-9d1bb1cae34b</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>283a272f-1c31-4ecc-b58e-3941cbdae994</id>
      <masked>false</masked>
      <name>officeCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>57ca4c8a-8238-4251-87d2-13d4e4b7cf58</id>
      <masked>false</masked>
      <name>serviceOfficeCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2d8cea31-a154-40c0-b4f5-61a45b304117</id>
      <masked>false</masked>
      <name>createdBy</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fdff74fa-e186-45df-8844-5bb2ad963131</id>
      <masked>false</masked>
      <name>custId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ae3515dd-1dfb-4f5e-9cf3-80b178d28102</id>
      <masked>false</masked>
      <name>custName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2bf4e533-ae5b-4273-ae80-e44135ae5978</id>
      <masked>false</masked>
      <name>custNikName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>19c3484c-6c1d-489b-a2e5-a0e0a4f63e45</id>
      <masked>false</masked>
      <name>birthDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2882dc7d-0850-4c00-b3c3-5ccbb1c6e125</id>
      <masked>false</masked>
      <name>birthPlace</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b5cc26ae-12a4-4d7f-b466-64a47324034a</id>
      <masked>false</masked>
      <name>sex</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8fdbbad6-9619-4a00-8d96-8576eecf93a1</id>
      <masked>false</masked>
      <name>mothersName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>34ab3a80-fdbc-4451-96f8-559e7208b910</id>
      <masked>false</masked>
      <name>objectCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2c29348d-7569-408d-a3a5-b105d5e7d741</id>
      <masked>false</masked>
      <name>objectGroup</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>874fd635-4bcb-473b-a3ca-0a2e94ead495</id>
      <masked>false</masked>
      <name>objectPrice</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>98f33dca-1383-42de-8849-aba9e20eb24e</id>
      <masked>false</masked>
      <name>noRangka</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4ad2bef5-9720-4b45-88af-c8ee7a50b474</id>
      <masked>false</masked>
      <name>noMesin</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dbbeb2a0-a136-46cb-899f-217833779773</id>
      <masked>false</masked>
      <name>bpkbSameName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>97a1f319-927a-48a2-83b1-da926e2325b3</id>
      <masked>false</masked>
      <name>amountToBeTransfer</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d8ac9eae-b91f-475a-8588-ea08682278d9</id>
      <masked>false</masked>
      <name>amountCreditObjective</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f2d03f3c-3dab-456b-b4de-db82f0ccfdc4</id>
      <masked>false</masked>
      <name>tenor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f7eccc62-7be0-43ae-961a-5847f4452462</id>
      <masked>false</masked>
      <name>top</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f6c7aca1-0662-41c1-bbd1-4e062ddac330</id>
      <masked>false</masked>
      <name>periode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>99f284c3-24ca-4cc9-b8ad-6c489016cdf8</id>
      <masked>false</masked>
      <name>monthInst</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>48a4f153-bd9e-484c-af75-f9a0be6b4a2b</id>
      <masked>false</masked>
      <name>flagTransfer</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f8b1c058-6875-40e8-b1be-aaa103f84135</id>
      <masked>false</masked>
      <name>sourceInputOri</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e55c1165-354a-446f-8536-e56cf676af8a</id>
      <masked>false</masked>
      <name>flagClp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6e5ab165-37df-4cc1-b723-7d9b093a4418</id>
      <masked>false</masked>
      <name>matchingFlagClp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bac275ac-f38c-4533-b573-4c8ee19c35a1</id>
      <masked>false</masked>
      <name>flagCloseOpen</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f43df6bb-a7a8-4321-83f0-c92548da0ccf</id>
      <masked>false</masked>
      <name>branchID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1c823264-d116-4632-b06f-d388a6c22754</id>
      <masked>false</masked>
      <name>angBerjalan</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>16770cde-7a07-4553-8657-73ebc82176b1</id>
      <masked>false</masked>
      <name>contractActDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d721388a-a230-4ac0-8d87-33d4feb376f1</id>
      <masked>false</masked>
      <name>ssPokokHutang</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>20ff3013-47ef-4984-98c5-de15509eb966</id>
      <masked>false</masked>
      <name>interestType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ae10aec4-320e-4bf6-b616-861825eb0450</id>
      <masked>false</masked>
      <name>sisaTenor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>92ba5b70-b7d5-48f6-888e-6146eff7e62d</id>
      <masked>false</masked>
      <name>reffOrderNo</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>94956811-c1fa-42d4-a6ef-5180450d268f</id>
      <masked>false</masked>
      <name>totalHutang</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dd5008fb-3863-4965-8096-abae5c191d93</id>
      <masked>false</masked>
      <name>kontrakAktif</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>79c3e3b9-638f-4ae0-8054-d5f4c35f7f3e</id>
      <masked>false</masked>
      <name>timeSpanDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>94698ac8-50fb-4de4-8187-b703dcfd7471</id>
      <masked>false</masked>
      <name>platform</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>816176aa-29a2-4066-825b-c569bd224115</id>
      <masked>false</masked>
      <name>angsuranKe</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f8e1719c-3f34-4aa7-abd3-9b6640bd715d</id>
      <masked>false</masked>
      <name>bussUnit</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()
</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
