<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02_cbEmail</name>
   <tag></tag>
   <elementGuidId>3843c7a3-4d52-4492-837e-983d18a714a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'z-combobox-open']/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mPBE4c0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c168756b-3319-483c-b79f-920a502f0108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mPBE4c0</value>
      <webElementGuid>84abd631-352b-4632-99ab-673c268c8971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>18316262-fc9e-4286-bae8-15bdf9fcfb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EMAIL</value>
      <webElementGuid>7de55bbd-2e11-4699-a268-94efa17d0257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mPBE4c0&quot;)</value>
      <webElementGuid>e6e88aad-d1a0-4d19-b74d-bfd82ae0fd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mPBE4c0']</value>
      <webElementGuid>9bdc168e-d0c0-4786-8215-a832995d0de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mPBEv50-cave']/li</value>
      <webElementGuid>f718ead7-6419-4da1-880e-293448774541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Occupation harus diisi'])[1]/following::li[1]</value>
      <webElementGuid>a4198f78-276e-4f94-90db-ed4367ffa7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mPBE4c0', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>6a7e2108-123a-4243-b575-44f22cfdff48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAX'])[3]/preceding::li[1]</value>
      <webElementGuid>09ca5919-c244-41f9-83ad-2caebb8aad0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/ul/li</value>
      <webElementGuid>4e0fbf41-a01b-4db7-ba86-8c99193d6335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mPBE4c0' and (text() = 'EMAIL' or . = 'EMAIL')]</value>
      <webElementGuid>44144c12-d55b-4256-9725-8dd93a5c9de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
