<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07_chkPrimary1</name>
   <tag></tag>
   <elementGuidId>df0646d6-0610-4be9-af78-9b1b569e729b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mPBE970-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76fbf1a0-bd05-4302-8731-6e5850a44d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7b18435b-d694-46c7-9467-42e6c706fcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mPBE970-real</value>
      <webElementGuid>8b029e26-9769-4240-8608-4daf03848847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mPBE970-real&quot;)</value>
      <webElementGuid>b87f504d-d605-4de4-aced-2dfac87b0adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mPBE970-real']</value>
      <webElementGuid>4721d8be-c37b-4136-83ce-7e05a513bbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mPBE970']/input</value>
      <webElementGuid>17642112-e8ab-4ad4-8456-606ecd6a812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/span/input</value>
      <webElementGuid>28c86ffb-0fb1-4c1b-a730-124f75f34f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mPBE970-real']</value>
      <webElementGuid>4350bacc-7c09-464a-b987-b45849271f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
