<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08_chkPrimary2</name>
   <tag></tag>
   <elementGuidId>6571ac45-9630-4581-b9bc-980e40bfe5aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[5]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mPBEjb0-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d41f0ae6-84cc-4079-a2da-fa24d92243a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a6bd1300-e727-4f17-8644-1a3cd468a579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mPBEjb0-real</value>
      <webElementGuid>aa233738-69d2-4754-ab6c-80ef78df1383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mPBEjb0-real&quot;)</value>
      <webElementGuid>9fd5256b-9570-486e-8763-040860f04bd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mPBEjb0-real']</value>
      <webElementGuid>fe82af80-0a57-4a5e-9105-902518a17297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mPBEjb0']/input</value>
      <webElementGuid>90bc11b1-41bb-4283-9861-1b481423980f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/span/input</value>
      <webElementGuid>1c12ae22-6b5e-489d-afac-1335467a775e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mPBEjb0-real']</value>
      <webElementGuid>8edd63a2-58db-4bb2-8e48-5b1d373777f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
