<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09_chkPrimary3</name>
   <tag></tag>
   <elementGuidId>ba8d2928-0d64-4a4a-bc49-1fd826971226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[5]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mPBEan-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5eca5f0-ae59-420b-b5d8-fff301ed594e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b6696035-3ddf-4b58-b6a3-5765e2bb8324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mPBEan-real</value>
      <webElementGuid>0bc75059-b098-44e3-8759-7e87a93ce4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mPBEan-real&quot;)</value>
      <webElementGuid>e16d7b85-add9-46a1-bfed-7f2d41b93b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mPBEan-real']</value>
      <webElementGuid>f0f6b291-b0e8-4c4d-92b2-6b34c4a15a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mPBEan']/input</value>
      <webElementGuid>9684e737-d89d-495f-9f16-7b7838e8e30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/div/span/input</value>
      <webElementGuid>1885f438-1fb4-497e-9ce2-ab5d8c5ca7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mPBEan-real']</value>
      <webElementGuid>8fd1da28-0e0f-4eeb-bbc6-75b842331c8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
