<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10_chkSmartphone1</name>
   <tag></tag>
   <elementGuidId>68e4d7ab-fe2c-40a8-a193-a01f35972d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div/div[3]/table/tbody/tr/td[4]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mPBE490-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87539f55-7049-42a4-97f7-442f2f291bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a7d04f4a-aef6-42ef-98b4-2ea5e8ddc7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mPBE490-real</value>
      <webElementGuid>c7f6b62b-d3bb-4af0-a504-e37b28f89f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mPBE490-real&quot;)</value>
      <webElementGuid>dcc50397-fd07-402a-ae8e-3a29013e4124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mPBE490-real']</value>
      <webElementGuid>2f758526-d843-44e0-97d1-da83e1c53734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mPBE490']/input</value>
      <webElementGuid>45d5acea-de60-428c-911a-67a81fcb1605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/table/tbody/tr/td[4]/div/span/input</value>
      <webElementGuid>3cc051fe-df9d-4cfc-9392-93d55cdb161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mPBE490-real']</value>
      <webElementGuid>f1e48ef6-ab09-4e3f-aa3c-cd178f7f32d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
