<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11_chkSmartphone2</name>
   <tag></tag>
   <elementGuidId>8aaae6ca-1a68-47e7-822f-c99372221e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/table/tbody/tr[2]/td[4]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mPBEt40-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca1eb344-7ef7-4f9f-afef-435a5502faea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>919d13a2-814b-4488-b1bb-6ed00d5f7cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mPBEt40-real</value>
      <webElementGuid>68bcbe38-93f4-442a-bb94-aa1a549b3a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mPBEt40-real&quot;)</value>
      <webElementGuid>367e9d63-33ec-4ad0-ad7e-2de26b41b44d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mPBEt40-real']</value>
      <webElementGuid>d630bc32-9aad-4929-a8a9-3660fd355302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mPBEt40']/input</value>
      <webElementGuid>92a2a94c-4a2d-4543-a433-41a6ddbd33d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[2]/td[4]/div/span/input</value>
      <webElementGuid>ffce3e15-ae72-40fe-a93c-58cbca433ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mPBEt40-real']</value>
      <webElementGuid>b4fddc42-95ee-407c-8e15-c3018c3fc1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
