<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01_tab_CustomerJobInfodanFinancialIndividual</name>
   <tag></tag>
   <elementGuidId>74d8b6d9-161e-45c3-b81f-5fc807219e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='nRDQcf-cnt']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Customer Job Info dan Financial Individual' or . = 'Customer Job Info dan Financial Individual')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nRDQcf-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51ab8b0b-8a31-4320-9184-a4a11cc6cc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQcf-cnt</value>
      <webElementGuid>d6b3c0f4-b87e-468f-aadb-1898422c32b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>555070ec-e460-42b2-a8f2-c2c36debc754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Job Info dan Financial Individual</value>
      <webElementGuid>7cf98dd2-64f3-4ec7-8df2-68915e00ae1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQcf-cnt&quot;)</value>
      <webElementGuid>415859b7-464b-4f61-8496-53a58ae7fdab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='nRDQcf-cnt']</value>
      <webElementGuid>5f7bbe02-6135-4e38-84ea-655f96983cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nRDQcf-cave']/span</value>
      <webElementGuid>15c93c9a-35f8-4ba5-89ae-579555e5ebb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Individual'])[1]/following::span[1]</value>
      <webElementGuid>f2af59ea-3408-47f0-93a3-44e1211ae489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGULER'])[1]/following::span[8]</value>
      <webElementGuid>f2c383df-7e34-431f-a3b0-c4ad9a273d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency Info'])[1]/preceding::span[1]</value>
      <webElementGuid>a4db95b6-828c-4022-966f-9c860fef726c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Addresses and Contact Info'])[1]/preceding::span[2]</value>
      <webElementGuid>e94c1115-7d96-4324-b928-014405c64756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Job Info dan Financial Individual']/parent::*</value>
      <webElementGuid>29c21e9d-75b3-4d94-878e-5f265558e40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/ul/li[2]/a/span</value>
      <webElementGuid>df80b0dc-2789-4846-bec6-ba70dc0e8bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'nRDQcf-cnt' and (text() = 'Customer Job Info dan Financial Individual' or . = 'Customer Job Info dan Financial Individual')]</value>
      <webElementGuid>53f2ed45-f3bc-4641-aa61-e85c404d174d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
