<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>03_chk_IndividualJob</name>
   <tag></tag>
   <elementGuidId>a8e6d398-c56d-4ed4-b69c-3f6b93847490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'nRDQrd-real']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/table/tbody/tr/td/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nRDQrd-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>880399da-f748-4e0f-a4e9-a5bf8b0b378e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6ce662c4-1614-40b1-8000-9dea62228ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQrd-real</value>
      <webElementGuid>12c83a96-8c6b-421a-860a-c06d7c30bfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQrd-real&quot;)</value>
      <webElementGuid>63c59711-99ca-4ede-ba10-2f7b4940c8fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQrd-real']</value>
      <webElementGuid>9c657abb-45cb-41f6-a764-12b5a66ad0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nRDQrd']/input</value>
      <webElementGuid>a116487a-46e3-4251-abb1-cd7201a81543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/table/tbody/tr/td/div/span/input</value>
      <webElementGuid>1af02a37-002a-4b4a-bfb2-89121b042314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'nRDQrd-real']</value>
      <webElementGuid>9203c75a-9d77-4700-861f-b353291ee94d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
