<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04_cb_OccupationType</name>
   <tag></tag>
   <elementGuidId>585a75ba-7957-4061-b4de-00a9c50fcd2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/table/tbody/tr/td[2]/div/span/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nRDQtd-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nRDQtd-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fda2c540-58a6-45f6-ac99-722a91186033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQtd-btn</value>
      <webElementGuid>a616f4ab-d401-447e-b720-f1fb5cc24ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-button</value>
      <webElementGuid>3d475419-ec6a-4d30-9196-7fe46c95f216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQtd-btn&quot;)</value>
      <webElementGuid>e1ecb67a-f855-400b-a920-c088c444a2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nRDQtd-btn']</value>
      <webElementGuid>62a51d67-06e4-4d5a-b5a1-8769b0d83807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nRDQtd']/a</value>
      <webElementGuid>b5a8f67a-eacc-40ab-87ca-56d3d3227f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Address'])[1]/following::a[1]</value>
      <webElementGuid>61ea85ea-8b9b-4609-88bb-bcf5519ba319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[1]/following::a[1]</value>
      <webElementGuid>c9596a6d-e080-4b64-902c-bf2087516454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMPLOYEE'])[1]/preceding::a[1]</value>
      <webElementGuid>bfd741a4-1c19-4ea5-b522-a3511ee40573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NON EMPLOYEE'])[1]/preceding::a[1]</value>
      <webElementGuid>aff394a0-3cec-424c-8bf7-2acb1051d9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/table/tbody/tr/td[2]/div/span/a</value>
      <webElementGuid>d3579f7b-a318-4852-a73b-1b073659dfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nRDQtd-btn']</value>
      <webElementGuid>09af54f1-1e98-434d-8d0e-d10b6b5c17cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
