<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05_fld_CompanyBusinessName</name>
   <tag></tag>
   <elementGuidId>f57660eb-ab2d-449e-ae61-c01698f08e10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQvd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/table/tbody/tr/td[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fb43ab5-5162-4c68-a568-ac0080687017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQvd</value>
      <webElementGuid>852ee616-ef22-4430-a7a2-7c154e898448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>fab1cd85-1ffc-4ce2-b725-29ba2c5c6549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f3ad8d3-45e2-48be-b750-465eab0ba29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>611160e6-ef5b-46b2-83c3-e564603856f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQvd&quot;)</value>
      <webElementGuid>5fe348c0-bd1a-4cce-bbfe-0f366e52d62a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQvd']</value>
      <webElementGuid>243f797d-b272-4fd7-ac4c-25351a7e3419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nRDQud-cave']/input</value>
      <webElementGuid>60f96eae-f02d-487b-80bb-0b56cbbe3975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[3]/div/input</value>
      <webElementGuid>1dd85e73-340c-4f8b-9a4e-e77e3f0504b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQvd' and @type = 'text']</value>
      <webElementGuid>588b25c7-ddda-4631-a1d4-e82586954d27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
