<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06_fld_SectorIndustry</name>
   <tag></tag>
   <elementGuidId>182f9391-e45e-455e-ab05-c61f65e68ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQxd-real</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/table/tbody/tr/td[4]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90c7232b-db94-4d23-b587-f007b7d9aa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQxd-real</value>
      <webElementGuid>6c35053b-d1dc-4d85-bad1-6bfbb6624362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-bandbox-input</value>
      <webElementGuid>4cca513f-c3aa-4400-a3af-bf980302c853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14ff9ebe-8405-4945-a3c0-666b3af71246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>928533bd-a213-4636-ac8d-efc88f8e9fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>6536e7ac-9bfa-4672-ac60-c1f1cbb465fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQxd-real&quot;)</value>
      <webElementGuid>49680a61-db64-48e8-b4b4-b6ec845a60b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQxd-real']</value>
      <webElementGuid>a1ab5d7c-d5d2-4e71-aaf9-3ac720d16c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nRDQxd']/input</value>
      <webElementGuid>01a17cea-b531-4b9c-a5b9-b55c6e9e658e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[4]/div/span/input</value>
      <webElementGuid>af3e4cb6-d2af-475e-8549-033230ea0ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQxd-real' and @type = 'text']</value>
      <webElementGuid>645a3cfd-eefe-4129-b6c9-a79239c790ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
