<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08_fld_DescriptionSectorIndustry</name>
   <tag></tag>
   <elementGuidId>56ab8a14-8054-4bb9-b019-4c9befb778d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQqx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/div/div[3]/table/tbody/tr[2]/td/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e48fa626-c51a-4eb4-b766-3edac557552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQqx</value>
      <webElementGuid>ffaf8f60-a5f4-4ce7-ab44-410d48344075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>2ce5f1c5-0af9-459f-ad34-80b7b6a503e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b59280a9-d49d-4b14-b0b8-ae8237aab7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQqx&quot;)</value>
      <webElementGuid>e929d0cc-b3fd-4f9c-8d20-e32d3175c041</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQqx']</value>
      <webElementGuid>c86ebaff-029a-4802-ae0d-ca35213238f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nRDQqx-cell']/input</value>
      <webElementGuid>a47b878f-eaad-4c4d-ae7f-147582b8bf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[3]/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>41640795-d143-4157-bd70-ae126109e653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQqx' and @type = 'text']</value>
      <webElementGuid>27d9b52a-a9f4-47c2-9a20-de6db70f0b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
