<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10_btn_SectorIndustryRow1</name>
   <tag></tag>
   <elementGuidId>643264e4-e6b2-49bd-8648-651015fb3405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQ_w-cave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div[4]/table/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a22d27b-0dba-44c0-b58e-9fb581566fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQ_w-cave</value>
      <webElementGuid>c9a80ce5-242f-43fe-a4a2-3575d3332654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-listcell-content</value>
      <webElementGuid>7744540c-8d5f-461d-9dac-0dd2339e213f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            01</value>
      <webElementGuid>77703c59-f607-4635-b7f9-5e20c19fc7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQ_w-cave&quot;)</value>
      <webElementGuid>69f63ee8-399c-481d-8eb1-1f92eb182aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nRDQ_w-cave']</value>
      <webElementGuid>17de58ed-7a25-4953-8e8f-3ecc585220de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='nRDQ_w']/div</value>
      <webElementGuid>4c8234f1-70fb-437b-bd01-6e9d07b54fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::div[3]</value>
      <webElementGuid>a71b1c71-6fab-42cc-890d-6f668857c46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/following::div[5]</value>
      <webElementGuid>2de02f3a-7796-4015-9195-569c85c60a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERTANIAN'])[1]/preceding::div[1]</value>
      <webElementGuid>dd689d23-d272-4c3d-bc9c-0b3edf649d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERTAMBANGAN'])[1]/preceding::div[3]</value>
      <webElementGuid>3e80ea56-07f9-42ef-a6f0-b6fe160e8210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/table/tbody/tr/td/div</value>
      <webElementGuid>5f78fe0a-0757-4772-88a4-a7ef01c9d712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nRDQ_w-cave' and (text() = '
                            01' or . = '
                            01')]</value>
      <webElementGuid>122f6364-27a7-40a1-b183-5d1f3da22eaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
