<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11_fld_SubSectorIndustry</name>
   <tag></tag>
   <elementGuidId>25b013fa-40c7-4a29-bbd1-ef5eca6c5261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQkx-real</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/table/tbody/tr/td[5]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80a0d082-64b1-4456-b7c3-315e768ae4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQkx-real</value>
      <webElementGuid>0c6d993c-bb88-4e73-acbf-7a8a1968fc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-bandbox-input</value>
      <webElementGuid>2400bce0-3b15-4a53-968a-ddfee894dfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7779b9df-ffd1-4136-8fda-199d9657a194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92e2a662-536f-4590-b190-95e12cf83cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e3636b7e-b11e-49ee-bed9-afcee361d87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQkx-real&quot;)</value>
      <webElementGuid>7273d520-fb11-4666-837f-0a1b48b1acbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQkx-real']</value>
      <webElementGuid>ecc3935e-7b53-4bf2-b4ba-f9b201abae03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nRDQkx']/input</value>
      <webElementGuid>a5fcd127-0020-4457-b0f2-00c7fcd21690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/table/tbody/tr/td[5]/div/span/input</value>
      <webElementGuid>3a923caa-acba-4532-ba5b-c9aa55792ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQkx-real' and @type = 'text']</value>
      <webElementGuid>ae475d80-4277-4bbe-a17e-4334ca9333d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
