<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12_fld_CodeSubSectorIndustry</name>
   <tag></tag>
   <elementGuidId>25367133-89bc-4235-b371-abd02280f18f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nRDQ2e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nRDQ2e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6085ec5e-c320-479f-9260-86a886c9f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQ2e</value>
      <webElementGuid>04e94b84-6b72-423b-adc0-4a70de1beeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>f99ed21f-1612-4a93-af18-d458f8f67739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>355ca69e-c5f4-4379-bfe7-4d68b8c3c483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQ2e&quot;)</value>
      <webElementGuid>b043c474-420a-4fe1-8709-2238d877f2ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQ2e']</value>
      <webElementGuid>074160ee-e2d3-4711-9c0b-afd3f796f879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nRDQ2e-cell']/input</value>
      <webElementGuid>070136fa-e14e-4991-b540-49b5bdc5d480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[3]/table/tbody/tr/td/div/input</value>
      <webElementGuid>83beb756-766f-4aa0-9b73-9b951c093297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQ2e' and @type = 'text']</value>
      <webElementGuid>2b97043a-1e66-4680-9d3f-d7f7c443b46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
