<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>13_fld_DescriptionSubSectorIndustry</name>
   <tag></tag>
   <elementGuidId>e330b572-03c3-4b2b-b932-28fe429087bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQ4e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/div/div[3]/table/tbody/tr[2]/td/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d74dfbc1-996e-4ccc-b923-7ce51149d5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQ4e</value>
      <webElementGuid>af2eb3f0-b76a-49d2-8a89-e826c65d8351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>1c035091-5c44-4567-aa30-3e10f271b971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4be1ee9f-5d08-4a08-a2ab-4070105967d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQ4e&quot;)</value>
      <webElementGuid>4007daef-71a2-4e46-ad52-615956ca0378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQ4e']</value>
      <webElementGuid>d552d4d7-73e1-4986-b6e2-4efa00ff1ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nRDQ4e-cell']/input</value>
      <webElementGuid>810545d6-0c10-4c96-a476-6a17b971a4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[3]/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>4a44faff-42a0-4b71-9ca3-61a720cd5373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQ4e' and @type = 'text']</value>
      <webElementGuid>807fad04-5264-4819-93dd-01320444c8d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
