<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15_btn_SubSectorIndustryRow1</name>
   <tag></tag>
   <elementGuidId>a07a36a3-7679-4e74-9979-3691953c8299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQie-cave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div[4]/table/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9db22cef-2106-4944-a24f-a762e406d87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQie-cave</value>
      <webElementGuid>4be866c7-73c6-4d35-a78d-3957647b3457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-listcell-content</value>
      <webElementGuid>611ffd06-314a-41cf-8eb5-2dfb190b01e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            01</value>
      <webElementGuid>fe4531e9-20fc-469e-8e22-338eab01b1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQie-cave&quot;)</value>
      <webElementGuid>792c0aa0-0e90-48ca-9fab-3aa3cbaf2ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nRDQie-cave']</value>
      <webElementGuid>10ba8ba1-cbcd-47c8-8194-40ca227179f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='nRDQie']/div</value>
      <webElementGuid>c5008ea0-3287-4f07-890c-ba2cafd557f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::div[3]</value>
      <webElementGuid>86ce48d5-3994-4ae7-80cf-993abb42c05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/following::div[5]</value>
      <webElementGuid>3f6fc895-e454-4410-a511-f48f30d55882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertanian tanaman, peternakan, perburuan dan kegiatan YBDI'])[1]/preceding::div[1]</value>
      <webElementGuid>bafca219-f0b5-43ae-bfcf-c1e5f8a99769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/ 1'])[20]/preceding::div[2]</value>
      <webElementGuid>b58f3e2d-1917-441b-829a-ca2fb4bbe3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/table/tbody/tr/td/div</value>
      <webElementGuid>5b93ad34-844d-4c75-a286-7337f4d125b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nRDQie-cave' and (text() = '
                            01' or . = '
                            01')]</value>
      <webElementGuid>11a4ba33-7db3-4005-901a-191d7463bb65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
