<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>17_fld_WorkEstablishSince</name>
   <tag></tag>
   <elementGuidId>1f2c4edc-22e8-4947-bf94-c3dd15292315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQ5c-real</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[7]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e9bb8ec-cb72-4ecc-b454-6b77656cf24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQ5c-real</value>
      <webElementGuid>a38cb8b4-ad33-4239-afde-d6dce8c3f808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-datebox-input</value>
      <webElementGuid>a5f2a70d-da88-499d-bd2a-607218854db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d6f4a54-baad-4e98-b770-02f230f67fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5d50631-e308-41e3-aead-96e1e94f9869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>fe18e6c8-98b9-4882-9e2d-d51623f26313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQ5c-real&quot;)</value>
      <webElementGuid>363592c5-a878-4da8-ba18-0e008119b7c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQ5c-real']</value>
      <webElementGuid>3d43d81e-6f1b-469e-a42c-5b5dcfb52d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nRDQ5c']/input</value>
      <webElementGuid>5fe6425a-5c47-4442-b6ae-b7629ba02745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/span/input</value>
      <webElementGuid>176f4375-bce1-4ffa-9e4d-176c9092f2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQ5c-real' and @type = 'text']</value>
      <webElementGuid>f09dcb43-b421-4dbf-b670-2348fa1ef1df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
