<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18_fld_SalesTurnoverIncome</name>
   <tag></tag>
   <elementGuidId>f34c1b72-2550-4ab7-afe8-d17bb5505cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nRDQ7c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[8]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de7166dc-c461-4cd4-a29c-cd4fc11665e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQ7c</value>
      <webElementGuid>604e3fab-9752-46dd-b954-7d54b08b312a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-decimalbox</value>
      <webElementGuid>666bf93e-eb34-41b1-aa55-7ce3258f6be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd1efa2d-5889-418c-824c-939a15c0764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>0937891a-7a34-4d97-a41d-33adcbad6130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>0ce279c1-56a8-43c0-be6a-74be14c7096c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQ7c&quot;)</value>
      <webElementGuid>be4f368b-7abb-4503-9a0c-8070287049b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQ7c']</value>
      <webElementGuid>ee5b72e9-9faf-4c4a-9867-1b4bfa57a1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nRDQle-cave']/input</value>
      <webElementGuid>bbd7a7ab-82a0-49da-bcd7-f45b3cf03c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>8b1d328c-9b7b-4236-be94-6b9b3d3d4790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQ7c' and @type = 'text']</value>
      <webElementGuid>58e8d3e8-5416-407d-b235-0722c6be2da9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
