<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>20_fld_CompanyAddress</name>
   <tag></tag>
   <elementGuidId>41a90649-91ef-413e-9d62-bc0288c033b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[10]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nRDQeb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0da2ba54-7b0b-420f-9332-f7bee991d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nRDQeb</value>
      <webElementGuid>271439d0-557d-4299-997c-e84e694278e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>ae4b4521-5b31-4b40-ad2f-168cd96f393f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01fff4a7-8459-497b-92c4-442e58184bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>42baad18-e63e-4e78-a51a-e2dee43fbfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nRDQeb&quot;)</value>
      <webElementGuid>6c5c1a18-7f37-497f-96fa-5ccb03943a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nRDQeb']</value>
      <webElementGuid>98ae0ac1-27d2-46c6-8605-b82033057b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nRDQac-cave']/input</value>
      <webElementGuid>d5ba827f-3cc1-406a-93a7-ef155d8fd5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/input</value>
      <webElementGuid>ef1cac73-c00d-4ce8-9973-21bea6249ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nRDQeb' and @type = 'text']</value>
      <webElementGuid>79be729c-11fb-43c0-8a5c-be19aed660f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
