<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>21_cb_OccupationType_EMPLOYEE</name>
   <tag></tag>
   <elementGuidId>48b226a2-94a5-48ea-aa9f-376ae3797ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = '${occupationType}' or . = '${occupationType}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[contains(@class, 'z-combobox-open')]/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b6SW5e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b81ca090-4f4d-41cb-b695-670f54aa9e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b6SW5e</value>
      <webElementGuid>a74f6c11-2526-4038-8871-22a169bacb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>154c82fd-826e-4c5c-a385-532c8f5206a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${occupationType}</value>
      <webElementGuid>b712c136-ccb5-4130-bf30-8ecb53e1caf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6SW5e&quot;)</value>
      <webElementGuid>a3aa9283-67e4-4d33-8e2d-adae9453cd3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='b6SW5e']</value>
      <webElementGuid>1177d745-1992-458f-a247-787826d946a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='b6SWtd-cave']/li</value>
      <webElementGuid>835e4cd8-fd3f-494b-a862-01f6fba7259c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b6SW5e', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>a429aa35-e9ad-48b1-912a-1dbb435ad2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      <webElementGuid>902bec8b-455d-429d-be75-53a50f7d98b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NON EMPLOYEE'])[2]/preceding::li[1]</value>
      <webElementGuid>2991611c-4728-4abe-8683-b802b5152e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li</value>
      <webElementGuid>691f5d1f-82db-4c42-9105-ed4942813bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'b6SW5e' and (text() = 'EMPLOYEE' or . = 'EMPLOYEE')]</value>
      <webElementGuid>61dea91a-028d-4536-8fd2-3a1e8c0d9a1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
