<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01_cb_BorrowerIncome</name>
   <tag></tag>
   <elementGuidId>eac6ac8c-9051-44fd-bb18-d51f1dc920f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[2]/td[2]/div/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @readonly = 'readonly' and contains(@placeholder, '- Please Select -')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a1GQ6o-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>306c0755-02d0-46e6-8e4e-9e0b8e8e0e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1GQ6o-real</value>
      <webElementGuid>ed74ae41-fec6-4ed8-b81c-50d43fdeefe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-input</value>
      <webElementGuid>692f7123-d9e3-4532-abe0-15f76905a666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7c062bf7-cf58-4c08-b729-a80945620c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f67c225b-f57d-4b12-8234-18bfe11d08de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>dee11487-89c3-4a99-b8be-4d5926a40b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>- Please Select -</value>
      <webElementGuid>204b3ba0-38bd-4719-8072-b3b7e69d2434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1GQ6o-real&quot;)</value>
      <webElementGuid>f222fac9-a389-458e-87d2-503f6a1122d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1GQ6o-real']</value>
      <webElementGuid>57bb6d7f-2b9b-495a-88f0-feed3d0687ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a1GQ6o']/input</value>
      <webElementGuid>9740b251-c283-4680-8ce9-1b27c0d1f848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[2]/td[2]/div/span/input</value>
      <webElementGuid>74b4860c-497b-4582-8e51-be045bcdaa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a1GQ6o-real' and @type = 'text' and @placeholder = '- Please Select -']</value>
      <webElementGuid>e691eb35-e4af-4ee1-b490-5eab5274221a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
