<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02_cb_SpouseIncome</name>
   <tag></tag>
   <elementGuidId>e363ffaf-f8a1-471d-9728-92d3fdccdd88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[3]/td[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a1GQdo-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef48edd1-deae-4ac6-b680-95c1e5323bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1GQdo-real</value>
      <webElementGuid>a53b3ed6-896a-406b-a3fd-4c2229095494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-input</value>
      <webElementGuid>b5e29c69-8c87-4ad8-8662-2d2ed07895a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>442c6ca9-8868-4e52-9f02-46748369e7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29a32c62-6c09-4569-8acd-f99bd00da269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e9602872-423f-4cc8-9d7f-4bc1bac9a546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>- Please Select -</value>
      <webElementGuid>855c6bb1-bdcb-494e-8bea-41c4fc6cc81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1GQdo-real&quot;)</value>
      <webElementGuid>de044a13-27c3-4129-a3dc-84b649e0892f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1GQdo-real']</value>
      <webElementGuid>a8347cbb-ee3e-427b-ba53-5955f4ac4f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a1GQdo']/input</value>
      <webElementGuid>e3748576-df3d-47b0-8733-24766a624464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[3]/td[2]/div/span/input</value>
      <webElementGuid>df4dafc5-4fe9-4c30-b799-b8e3d4529070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a1GQdo-real' and @type = 'text' and @placeholder = '- Please Select -']</value>
      <webElementGuid>bde97df0-f8b9-4117-ab48-634dba3b092d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
