<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>03_cb_OtherIncome</name>
   <tag></tag>
   <elementGuidId>0023b3bf-a479-4c74-a832-9134c009c0c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[4]/td[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a1GQko-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e00520eb-f50c-464b-a853-1a476bd81db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1GQko-real</value>
      <webElementGuid>be2777fc-56ce-44ed-83c1-c4a9fcea4d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-input</value>
      <webElementGuid>ef2567dc-7cc0-41ee-a941-9cab00f9d14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6613ef1b-5e17-447a-8953-70e8ef4cf96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9857b2f-c99d-46f8-a8b7-22e2a19cd463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>988715d6-2624-49d2-861e-43c7b68b4b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>- Please Select -</value>
      <webElementGuid>40ceb6a3-6d36-4c9e-ad27-5e845a5acd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1GQko-real&quot;)</value>
      <webElementGuid>9dea2a88-ff48-4e6d-b91b-05683a423e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1GQko-real']</value>
      <webElementGuid>0aaedcca-dddd-419f-b772-04021c46e0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a1GQko']/input</value>
      <webElementGuid>b9a66e7e-2fe6-4318-acb0-5cc7a29da885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[4]/td[2]/div/span/input</value>
      <webElementGuid>6fa97b81-5f8f-4540-9e9f-e11c2317306c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a1GQko-real' and @type = 'text' and @placeholder = '- Please Select -']</value>
      <webElementGuid>700b61af-07eb-44c8-b933-f2ce4d35a77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
