<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04_cb_Expense</name>
   <tag></tag>
   <elementGuidId>bbf94c3e-af8d-4b9a-956b-f303c8b16028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[5]/td[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a1GQro-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3233821c-c150-4435-9ba0-d4cfaee9a9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1GQro-real</value>
      <webElementGuid>deb45916-df02-47db-88d4-5fa65f227831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-input</value>
      <webElementGuid>caeb354f-c7bb-46d1-99a5-7c77acb5da19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>23551ad1-5a0e-4e0c-936f-e5367a2e86c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50260206-1bb9-4274-8b09-d250420ce242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f17c9629-4a01-42ea-8e2e-a50edc3d04a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>- Please Select -</value>
      <webElementGuid>eaa9a7d3-af1d-4d72-acaa-16034cc646c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1GQro-real&quot;)</value>
      <webElementGuid>bca8082e-d49b-431c-80b6-7da5ab7dcdda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1GQro-real']</value>
      <webElementGuid>c19348f0-cce4-4cd3-99b7-e2d91e99c2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a1GQro']/input</value>
      <webElementGuid>fc42f347-75bc-4294-b157-ec890557439e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/table/tbody/tr[5]/td[2]/div/span/input</value>
      <webElementGuid>375c5423-36d9-42a7-822a-088499fd4fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a1GQro-real' and @type = 'text' and @placeholder = '- Please Select -']</value>
      <webElementGuid>fa017253-8a21-4e21-9da8-c27bac9380af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
