<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08_fld_Expense</name>
   <tag></tag>
   <elementGuidId>46e01453-1af0-4f18-b5d6-28154d2e05d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[5]/td[3]/div/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#z1HQto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19974c58-c213-4047-979a-58370f48a3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>z1HQto</value>
      <webElementGuid>82c2364f-38f5-407e-9e82-078d5f145d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-doublebox</value>
      <webElementGuid>674dea48-b88e-47d0-a768-a9630fb4e5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58e1fa6a-50d9-449f-9ba9-0cdcb0e38bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>bb34d0a1-6d36-4d40-8424-80e1527edd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3199f5a0-8e42-4403-96d6-233318eef7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;z1HQto&quot;)</value>
      <webElementGuid>e4632832-6310-4989-8b61-e6d91128e3b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='z1HQto']</value>
      <webElementGuid>aa7fc7c6-30f3-4872-8921-f7fbf9e35a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='z1HQto-chdex']/input</value>
      <webElementGuid>e9694e94-f2f8-4df1-b898-e61331753065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/div/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>cf9203c7-b8bc-487c-bd40-ae19505bf9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'z1HQto' and @type = 'text']</value>
      <webElementGuid>b0257d20-441f-4471-bb3a-05fd7fc20a2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
