<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10_fld_SourceOfFund_SpouseIncome</name>
   <tag></tag>
   <elementGuidId>87a4a0fc-71e7-42dd-8ee2-fbb26c3c26f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[4]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#z1HQho</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70e6e9a0-63bc-4320-a562-d8f84988ec64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>z1HQho</value>
      <webElementGuid>e27e1f70-d7fb-436c-958c-02749e5a634b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>52f1b49d-4575-4da8-a74f-be00424526f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49d7c191-a470-478a-9adc-0f6b15244d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b3f2879f-8724-4d9e-8f01-d25e93c6a2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;z1HQho&quot;)</value>
      <webElementGuid>e81e5b5b-035c-40db-a2d7-1dcfce560a8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='z1HQho']</value>
      <webElementGuid>702896d1-3805-4c01-818f-f94e96afc065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='z1HQho-cell']/input</value>
      <webElementGuid>0c9960e0-0409-4c49-aa05-c4eb63cedaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/input</value>
      <webElementGuid>a6974abb-aeb5-49d7-b5f1-c3239a015fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'z1HQho' and @type = 'text']</value>
      <webElementGuid>2d664e4b-2359-464e-8186-5246cacb20ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
