<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11_fld_SourceOfFund_OtherIncome</name>
   <tag></tag>
   <elementGuidId>71f25ea0-26d8-4f03-ae2d-ce357e9b4daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[4]/td[4]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#z1HQoo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>584acc9e-3e13-4fd2-ad2e-8315e3cae47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>z1HQoo</value>
      <webElementGuid>7082f8ac-32ca-4138-8d70-5ae9768d05d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>6c2b2a3a-0992-4262-bce7-78d583ebe26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1d767ef-5bbd-498c-ad77-3b346085b486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>bebb2d14-6d38-4300-a0d2-42c40767e661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;z1HQoo&quot;)</value>
      <webElementGuid>61a6b05e-4aec-4d7a-8fc8-efa3a285364a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='z1HQoo']</value>
      <webElementGuid>25f25e96-a735-42dd-8098-c09e9eb1918c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='z1HQoo-cell']/input</value>
      <webElementGuid>1873329d-08f6-4489-897b-ac630cea21bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/div/input</value>
      <webElementGuid>1fa17ab7-d42a-41ba-872c-1e3165ad3f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'z1HQoo' and @type = 'text']</value>
      <webElementGuid>14d5e8cc-0e5b-436d-819e-a0cc53fd7b21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
