<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12_btn_Add Row</name>
   <tag></tag>
   <elementGuidId>08d80a6e-c64c-4cde-946f-be2942a51285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='z1HQdp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#z1HQdp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab96446e-9c41-4a72-a336-412f614c446e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>532f4bfe-9ef2-4297-b3c6-fe6e0600fa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>z1HQdp</value>
      <webElementGuid>cf983d17-f1e5-4281-9a2a-0383850f40e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>cec7024f-feaf-4e27-97cb-6810e3545c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Row</value>
      <webElementGuid>7f1fe563-89b2-4f83-ba0a-e2dd6b5af936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;z1HQdp&quot;)</value>
      <webElementGuid>d141b432-c5b6-4acb-b768-a9b7879087d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='z1HQdp']</value>
      <webElementGuid>1f96211e-98ab-4b69-8957-2af7eb5a317a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='z1HQdp-chdex']/button</value>
      <webElementGuid>47d86722-ec6c-4b10-acae-1193c20edb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data Found'])[9]/following::button[2]</value>
      <webElementGuid>4c452c80-cefc-4cd9-936c-54c925e592a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/following::button[2]</value>
      <webElementGuid>d849a08b-a323-43b6-9a8d-f5b738238e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/preceding::button[1]</value>
      <webElementGuid>7aaa0ae1-282e-46d1-9027-eb46fff2cd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Bank Account'])[1]/preceding::button[2]</value>
      <webElementGuid>7a4f1831-76be-499b-b4e6-ade6fbacfeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr/td/table/tbody/tr/td/button</value>
      <webElementGuid>d01cea09-a8ce-410b-aeda-09a59b578b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'z1HQdp' and (text() = ' Add Row' or . = ' Add Row')]</value>
      <webElementGuid>0bdae4b0-ecce-4ea5-bb07-3d1c532d0be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
