<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>13_fld_Bank</name>
   <tag></tag>
   <elementGuidId>fba1a65d-1ffc-441c-bea6-2f0d78b8349b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/table/tbody/tr/td[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vS7Prd-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1073ddc-5198-4ade-8e9e-ae11c1c3abc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vS7Prd-real</value>
      <webElementGuid>2725ce5b-a8f5-4acc-a9bb-7d6bf0a3e307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-bandbox-input</value>
      <webElementGuid>30d193f8-ee79-4235-a24d-bebc3c5b6cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1fa3d151-5391-444d-819e-cdc0edc7f6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a86b3d1e-442e-45b2-aef9-ee30efbc66ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>9d7fc6c5-5a02-43b6-87d0-0d49949a38fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vS7Prd-real&quot;)</value>
      <webElementGuid>c7aa2467-8890-49b0-84ec-246fd0f298cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vS7Prd-real']</value>
      <webElementGuid>448bc406-1f7f-4ff0-85b4-af25bcb3fc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='vS7Prd']/input</value>
      <webElementGuid>6429f243-61e0-4446-850d-d74bd2c682cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/table/tbody/tr/td[2]/div/span/input</value>
      <webElementGuid>97012e2c-542c-4f4a-9981-665662dd4ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vS7Prd-real' and @type = 'text']</value>
      <webElementGuid>238d2403-fb78-45e8-94fc-83bdf38bd595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
