<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>14_fld_BankID</name>
   <tag></tag>
   <elementGuidId>cdb38f3e-448c-43de-82e5-68caea63f21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vS7Pzv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vS7Pzv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c89bb099-bba4-475d-be55-67a8a79eb845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vS7Pzv</value>
      <webElementGuid>5b934a02-376b-4993-aee3-a21eb07de1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>5a7359c8-b800-437c-b1d7-07770a80a560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>312eb1e1-bb54-4278-b380-b8bd616495c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vS7Pzv&quot;)</value>
      <webElementGuid>1a937db8-ed83-491f-921d-99961e46c363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vS7Pzv']</value>
      <webElementGuid>6ff109f7-61ce-49a5-806f-bfe2ab376912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vS7Pzv-cell']/input</value>
      <webElementGuid>0020ad39-364a-4a4e-8652-8fbae366f3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[3]/table/tbody/tr/td/div/input</value>
      <webElementGuid>f7e016c0-d2f7-4262-8a09-27857cd1e7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vS7Pzv' and @type = 'text']</value>
      <webElementGuid>ce195c23-2a2c-4023-bf4b-789e5b94be7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
