<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15_fld_BankName</name>
   <tag></tag>
   <elementGuidId>fcc51ff3-b025-4fdb-bd4d-a01b49ef7221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vS7P0w']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vS7P0w</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28c5f1c9-147c-41af-b773-02e488423f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vS7P0w</value>
      <webElementGuid>b38003dd-9bb5-43ed-93ad-df1d63f8da64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>e78e30b8-8292-4907-af72-ecdd53c46b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ab27ea7-1fb5-42f4-82d6-ded77f9edee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vS7P0w&quot;)</value>
      <webElementGuid>42ef27dd-259a-4928-8060-8f8d5cc737fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vS7P0w']</value>
      <webElementGuid>332b99e3-77a8-41c2-972f-1e0a8760ba18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vS7P0w-cell']/input</value>
      <webElementGuid>10cb12b9-b2a7-4b1f-b71a-f61799920f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[3]/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>731aca78-e7ea-474b-a69c-c741f76bf184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vS7P0w' and @type = 'text']</value>
      <webElementGuid>257a6776-bb75-4d18-b8d4-529dd10c4782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
