<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>17_btn_BankRow1</name>
   <tag></tag>
   <elementGuidId>809d9dc7-46a8-4ec3-a70b-9b1022872669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div[4]/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vS7P1b0-cave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a61d9f3-6947-4032-af40-5479cf658f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vS7P1b0-cave</value>
      <webElementGuid>8215f954-951e-43d2-a56b-d224be49dec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-listcell-content</value>
      <webElementGuid>2e46f25c-4934-41c1-8f8e-59b960f34bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            AA001</value>
      <webElementGuid>ad0cbf6e-db3c-4e61-b258-b89877e8cb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vS7P1b0-cave&quot;)</value>
      <webElementGuid>234658cf-45ee-41e5-91b0-6e4004656e85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='vS7P1b0-cave']</value>
      <webElementGuid>a7814570-2a38-42e7-873a-2ecb5e497f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='vS7P1b0']/div</value>
      <webElementGuid>f28f2fa1-fa5b-4f3e-8e93-d10b47d82a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Name'])[3]/following::div[3]</value>
      <webElementGuid>85b8a23d-b8ff-4873-9923-5d1ad5a81b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank ID'])[2]/following::div[5]</value>
      <webElementGuid>58833a53-cd4b-4708-9151-30a724bff956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUMI ARTHA'])[1]/preceding::div[1]</value>
      <webElementGuid>83635ba3-f44d-476b-a0f0-07f9fb2bbeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/table/tbody/tr/td/div</value>
      <webElementGuid>00cafc12-2c18-4aa0-9ad9-dc4d3d25dc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'vS7P1b0-cave' and (text() = '
                            AA001' or . = '
                            AA001')]</value>
      <webElementGuid>3b90684b-b489-468d-bcf1-16a34d51bf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
