<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>28_cbAlBaiWaAlIstijar</name>
   <tag></tag>
   <elementGuidId>8b8a255e-9096-4c3e-b7c1-26d8b826cb2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'z-combobox-open')]/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mNUF380</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7e20bbc7-a2e7-495f-8a62-77bad364a57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mNUF380</value>
      <webElementGuid>02542522-0665-433e-90bc-b3def7d4a28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>3d2d6687-07c4-492d-9f64-c960c937471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AL BAI WA AL ISTIJAR</value>
      <webElementGuid>03abeb98-fb0c-4de1-b807-308cde079079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mNUF380&quot;)</value>
      <webElementGuid>d483ccad-042c-44ac-8c9a-15ad494361d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mNUF380']</value>
      <webElementGuid>75f7f250-0736-401c-8ef0-12492ffac536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mNUFki-cave']/li</value>
      <webElementGuid>b1ee94c1-d0ff-45ec-9e1c-85221b76fb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>63641a46-9783-45a1-9c64-bbf5cc71729b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::li[1]</value>
      <webElementGuid>6c399401-7ee2-41d2-8ab0-98ead6d351d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUSYARAKAH MUTANAQISHAH'])[1]/preceding::li[1]</value>
      <webElementGuid>ab5016b0-3796-49bf-aeb0-9e5a8516cbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li</value>
      <webElementGuid>ff144967-2b97-4bb6-9db5-bba4acf91f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mNUF380' and (text() = 'AL BAI WA AL ISTIJAR' or . = 'AL BAI WA AL ISTIJAR')]</value>
      <webElementGuid>050253b3-5e1a-48a5-8f11-67fbe092817f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
