<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>29_cbMusyarakahMutanaqishah</name>
   <tag></tag>
   <elementGuidId>ceac088a-c833-43d7-9f68-f26e76e361ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/ul/li/span[contains(text(),'${subPlatform}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mNUF380</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>88e54fee-1c95-4f76-ae32-0e66bbe98b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mNUF380</value>
      <webElementGuid>8aa108d7-50d8-438d-a7e7-4e610fed0654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>f4f1c9d2-4954-44dc-942a-936224e147c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AL BAI WA AL ISTIJAR</value>
      <webElementGuid>6cf0f9aa-d885-4f44-857b-94d7b2f3ab20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mNUF380&quot;)</value>
      <webElementGuid>5fcbfe1a-a546-4ce3-9631-002582add371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mNUF380']</value>
      <webElementGuid>22a78d99-b550-4cec-8910-759ab3d03598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mNUFki-cave']/li</value>
      <webElementGuid>7521b39d-c60c-4c27-8694-f6014fdb5b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>7aa3df0c-4696-4538-8809-4c40062a3c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::li[1]</value>
      <webElementGuid>45f9e8e5-733d-4b0f-863f-a78462d7dcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUSYARAKAH MUTANAQISHAH'])[1]/preceding::li[1]</value>
      <webElementGuid>e6206376-3696-47cd-9fac-683f28a669f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/ul/li</value>
      <webElementGuid>5fdc64ad-9aac-4554-af4e-104341b3ec57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mNUF380' and (text() = 'AL BAI WA AL ISTIJAR' or . = 'AL BAI WA AL ISTIJAR')]</value>
      <webElementGuid>a312aeb6-8b41-4340-b01d-e6227d6d5509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
