<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>42_chkMobilePhone2</name>
   <tag></tag>
   <elementGuidId>ee3b2a76-46bd-4a99-8f71-06e3d4d899d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[3]/div[3]/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[8]/div[2]/div[3]/div/div/div[2]/table/tbody/tr/td/table/tbody/tr/td[1]/div/div[2]/div[2]/div[3]/table/tbody[1]/tr[3]/td[2]/div/span/a[@class='z-combobox-button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
