<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>23_chkFirstContact</name>
   <tag></tag>
   <elementGuidId>07346b66-3645-40ac-9750-68bcfc1c549c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/div[1]/div[2]/table[1]/tbody/tr/td/table/tbody/tr/td[5]/table/tbody/tr/td/table/tbody/tr/td/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/table/tbody[1]/tr[1]/td[1]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
