<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07_rbCustDetail</name>
   <tag></tag>
   <elementGuidId>1700f737-a95e-492b-932e-810c699a803e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='z-page']/div/div/div[3]/div[3]/div/div/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/div[2]/div[3]/table/tbody[1]/tr/td[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@class='z-page']/div/div/div[3]/div[3]/div/div/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/div[2]/div[3]/table/tbody[1]/tr/td[7]</value>
      <webElementGuid>27adc34e-58fc-43ea-aa1b-8c9044cc79c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
